modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="tll_but_in_blocks"
version="1.0.0"
displayName="tll_but_in_blocks"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="rhuan, MCreator"

[[dependencies.tll_but_in_blocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




